name: Release

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get plugin version
        id: plugin-version
        run: |
          VERSION=$(grep -Eo "Version: [0-9]+\.[0-9]+\.[0-9]+" wp-magic-link-auth.php | cut -d " " -f 2)
          echo "::set-output name=version::$VERSION"

      - name: Get pull request description
        id: pr-description
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pr.data.body;

      - name: Create release zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: wp-magic-link-auth-${{ steps.plugin-version.outputs.version }}.zip
          exclusions: '*.git* .github/* release.yml'

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        with:
          tag_name: v${{ steps.plugin-version.outputs.version }}
          release_name: Release v${{ steps.plugin-version.outputs.version }}
          body: ${{ steps.pr-description.outputs.result }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./wp-magic-link-auth-${{ steps.plugin-version.outputs.version }}.zip
            asset_name: wp-magic-link-auth-${{ steps.plugin-version.outputs.version }}.zip
            asset_content_type: application/zip